version: '3'
services:
  rabbitmq:
    hostname: "{{.Node.Hostname}}"
    deploy:
      mode: global
      restart_policy:
         delay: 10s
    image: docker.io/warrior7089/rabbitmq:1.0
    healthcheck:
        test: ["CMD-SHELL", "rabbitmqctl node_health_check"]        
        interval: 1m
        timeout: 30s
        retries: 10
    networks:
      - default
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbitmq-data-etc:/etc/rabbitmq
      - rabbitmq-data-var:/var/lib/rabbitmq    
    environment:              
      - RABBITMQ_LOG_BASE=/var/log/rabbitmq        
      - RABBITMQ_CONFIG_FILE=/etc/customrabbitmq/customrabbitmq.conf
      - RABBITMQ_ERLANG_COOKIE=ATKLALLROLGHWFVLNTBY
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=pass
    logging:
      driver: "json-file"

volumes:
  rabbitmq-data-etc:
  rabbitmq-data-var:
